version: "3.8"
services:
  czechibank:
    container_name: czechibank-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=czechitasBank
      - POSTGRES_PASSWORD=czechitasBank
    ports:
      - "1111:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
